AWSTemplateFormatVersion: 2010-09-09
Description: >-
  tma
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  pStage:
    Description: Environment stage
    Type: String
    AllowedValues:
      - dev
      - prod
      - staging

Conditions:
  IsProdDeployment: !Equals
    - !Ref pStage
    - 'prod'
  IsStagingDeployment: !Equals
    - !Ref pStage
    - 'staging'
  ProdOrStaging: !Or
    - Condition: IsProdDeployment
    - Condition: IsStagingDeployment

Mappings:
  StageValueMap:
    dev:
      s3ResourcesBucket: dev-tma-files
      CdnOrigin: "dev-tma-files.s3.amazonaws.com"
      siteOrigin: "'http://localhost:3000'"
      apiStage: Dev
      applicationDomainName: 'dev.trinitymutualaid.com'
    staging:
      s3ResourcesBucket: staging-tma-files
      CdnOrigin: "cdn-staging.trinitymutualaid.com"
      siteOrigin: "'https://staging.trinitymutualaid.com'"
      apiStage: Staging
      applicationDomainName: 'staging.trinitymutualaid.com'
    prod:
      s3ResourcesBucket: prod-tma-files
      CdnOrigin: "cdn.trinitymutualaid.com"
      siteOrigin: "'https://trinitymutualaid.com'"
      apiStage: Prod
      applicationDomainName: 'trinitymutualaid.com'
  
Resources:
  TMAApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !FindInMap [StageValueMap, !Ref pStage, apiStage]
      Auth:
        AddDefaultAuthorizerToCorsPreflight: false
        DefaultAuthorizer: CognitoAuth
        Authorizers:
          CognitoAuth:
            UserPoolArn: !GetAtt TMAUserPool.Arn
  ArticlesCrudFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: app/
      Handler: dist/src/handlers/handlers.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 60
      Description: Lambda for CRUD operations on articles.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Articles
        - S3CrudPolicy:
            BucketName: !Ref S3ResourcesBucket
      Environment:
        Variables:
          ARTICLES_TABLE: !Ref Articles
          RESOURCES_BUCKET: !Ref S3ResourcesBucket
          CDN_ORIGIN: !FindInMap [StageValueMap, !Ref pStage, CdnOrigin]
      Events:
        Cors:
          Type: Api
          Properties:
            RestApiId: !Ref TMAApi
            Path: '/{proxy+}'
            Auth:
              Authorizer: NONE
            Method: OPTIONS
        Hello:
          Type: Api
          Properties:
            RestApiId: !Ref TMAApi
            Path: /hello
            Method: GET
        S3UploadUrl:
          Type: Api
          Properties:
            RestApiId: !Ref TMAApi
            Path: /file-upload
            Method: GET
        PutArticle:
          Type: Api
          Properties:
            RestApiId: !Ref TMAApi
            Path: /article
            Method: PUT
        PatchArticle:
          Type: Api
          Properties:
            RestApiId: !Ref TMAApi
            Path: /article/{articleId}
            Method: PATCH
        GetArticle:
          Type: Api
          Properties:
            RestApiId: !Ref TMAApi
            Path: /article/{articleId}/{language}/
            Auth:
              Authorizer: NONE
            Method: GET
        KeepAlive:
          Type: Schedule
          Condition: ProdOrStaging
          Properties:
            Name: !Sub KeepAlive${pStage}
            Description: Event on timer to keep lambda alive so never cold-starts
            Enabled: false
            Schedule: 'rate(1 minute)'
  Articles:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub tma-articles-${pStage}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
  S3ResourcesBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !FindInMap [StageValueMap, !Ref pStage, s3ResourcesBucket]
      AccessControl: PublicRead
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: ['GET', 'PUT', 'HEAD']
            AllowedOrigins:
              - 'http://trinitymutualaid.com'
              - 'http://www.trinitymutualaid.com'
              - 'http://staging.trinitymutualaid.com'
              - 'https://trinitymutualaid.com'
              - 'https://www.trinitymutualaid.com'
              - 'https://staging.trinitymutualaid.com'
              - 'http://localhost:3000'
            MaxAge: 3000
        
  BucketReadPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3ResourcesBucket
      PolicyDocument:
        Statement:
          - Action: 's3:GetObject'
            Effect: Allow
            Resource: !Sub 'arn:aws:s3:::${S3ResourcesBucket}/*'
            Principal: '*'
# =====================================
#    Cognito/User Pool Stuff
# =====================================
  TMAUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub TMAUserPool-${pStage}
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false
  TMAMobileWebClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref TMAUserPool
      ClientName: !Sub TMAMobileWebClient-${pStage}
      GenerateSecret: false
      SupportedIdentityProviders:
        - COGNITO
  TMAIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Sub TMAIdentityPool-${pStage}
      AllowClassicFlow: true
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref TMAMobileWebClient
          ProviderName: !GetAtt TMAUserPool.ProviderName
  CognitoUnAuthorizedRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Federated: "cognito-identity.amazonaws.com"
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "cognito-identity.amazonaws.com:aud": !Ref TMAIdentityPool
              "ForAnyValue:StringLike":
                "cognito-identity.amazonaws.com:amr": unauthenticated
      Policies:
        - PolicyName: !Sub CognitoUnauthorizedPolicy-${pStage}
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  # - "mobileanalytics:PutEvents"
                  - "cognito-sync:*"
                Resource: "*"
  CognitoAuthorizedRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Federated: "cognito-identity.amazonaws.com"
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "cognito-identity.amazonaws.com:aud": !Ref TMAIdentityPool
              "ForAnyValue:StringLike":
                "cognito-identity.amazonaws.com:amr": authenticated
      Policies:
        - PolicyName: !Sub CognitoAuthorizedPolicy-${pStage}
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "mobileanalytics:PutEvents"
                  - "cognito-sync:*"
                  - "cognito-identity:*"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "lambda:InvokeFunction"
                Resource: "*"
  IdentityPoolRoleMapping:
    Type: "AWS::Cognito::IdentityPoolRoleAttachment"
    Properties:
      IdentityPoolId: !Ref TMAIdentityPool
      Roles:
        authenticated: !GetAtt CognitoAuthorizedRole.Arn
        unauthenticated: !GetAtt CognitoUnAuthorizedRole.Arn

# =====================================
#    CloudFront/DNS Stuff
# =====================================
  ResourcesCloudFrontOriginAccessIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Condition: ProdOrStaging
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref S3ResourcesBucket
  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Condition: ProdOrStaging
    Properties:
      DistributionConfig:
        Aliases:
          - !FindInMap [StageValueMap, !Ref pStage, CdnOrigin]
        Enabled: true
        DefaultRootObject: '/index.html'
        Origins:
          - DomainName: !GetAtt S3ResourcesBucket.DomainName
            Id: trinitymutualaid.com
            S3OriginConfig:
              OriginAccessIdentity: !Join ['', ['origin-access-identity/cloudfront/', !Ref ResourcesCloudFrontOriginAccessIdentity]]
        DefaultCacheBehavior:
          TargetOriginId: trinitymutualaid.com
          AllowedMethods: ['GET', 'HEAD', 'OPTIONS']
          CachedMethods: ['GET', 'HEAD', 'OPTIONS']
          Compress: true
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          MinTTL: 60 # seconds
          DefaultTTL: 3600 # seconds
          MaxTTL: 86400 # seconds
          ViewerProtocolPolicy: 'redirect-to-https'
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: '/index.html'
        HttpVersion: http2
        # cheapest price class until we launch in Japan: https://aws.amazon.com/cloudfront/pricing/
        PriceClass: 'PriceClass_100'
        ViewerCertificate:
          AcmCertificateArn: 'arn:aws:acm:us-east-1:779912378635:certificate/521fbdb4-4c8d-4fd8-a510-ac50aa962f78'
          SslSupportMethod: 'sni-only'
  Route53Record:
    Type: "AWS::Route53::RecordSet"
    Condition: ProdOrStaging
    Properties:
      HostedZoneId: 'Z086888927BY7SP6PB8LV'
      Type: A
      Name: !FindInMap [StageValueMap, !Ref pStage, CdnOrigin]
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
        

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${TMAApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  TMAUserPoolId:
    Value: !Ref TMAUserPool
    Export:
      Name: !Sub "TMAUserPool-${pStage}::Id"
  TMAIdentityPoolId:
    Value: !Ref TMAIdentityPool
    Export:
      Name: !Sub "TMAIdentityPool-${pStage}::Id"
  TMAMobileWebClientId:
    Value: !Ref TMAMobileWebClient
    Export:
      Name: !Sub "TMAMobileWebClient-${pStage}::Id"
  S3UploadBucketName:
    Description: "S3 bucket for application uploads"
    Value: !Ref S3ResourcesBucket