name: S3-Update-Static

on:
  push:
    branches: 
      - main
      - develop

env:
  REGION: 'us-east-1'
  APPLICATION_DOMAIN_NAME: 'trinitymutualaid.com'

jobs:
  infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Configure AWS credentials for Prod
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Create change set in AWS CloudFormation
        if: github.ref != 'refs/heads/master' || github.event_name != 'push'
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: WebClientHostingInfra
          template: template.yml
          no-fail-on-empty-changeset: "1"
          no-execute-changeset: "1"
          parameter-overrides: >-
            pApplicationDomainName=${{ env.APPLICATION_DOMAIN_NAME }},
            pAcmCertificateArn=${{ secrets.ACM_TLS_CERTIFICATE_ARN }}
      - name: Deploy to AWS CloudFormation
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: WebClientHostingInfra
          template: template.yml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            pApplicationDomainName=${{ env.APPLICATION_DOMAIN_NAME }},
            pAcmCertificateArn=${{ secrets.ACM_TLS_CERTIFICATE_ARN }}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Activate Staging Build
        if: endsWith(github.ref, '/develop')
        env:
          ENV_FILE_STAGING: ${{  secrets.ENV_FILE_STAGING  }}
        run: |
          echo "AWS_S3_BUCKET=dev.trinitymutualaid.com" >> $GITHUB_ENV
          echo "$ENV_FILE_STAGING" | base64 -d > ./frontend/.env
      - name: ActivateProduction Build
        env:
          ENV_FILE_PRODUCTION: ${{  secrets.ENV_FILE_PRODUCTION }}
        if: endsWith(github.ref, '/main')
        run: |
          echo "AWS_S3_BUCKET=trinitymutualaid.com" >> $GITHUB_ENV
          echo "$ENV_FILE_PRODUCTION" | base64 -d > ./frontend/.env

      - name: Install and Build
        run: |
          cd ./frontend
          wc -m .env
          npm install
          npm run-script build
      - uses: awact/s3-action@master
        env:
          SOURCE_DIR: './frontend/build'
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  
