name: S3-Update-Static

on:
  push:
    branches: 
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: |
          echo Running npm commands
          cd ./frontend
          npm install
          npm run-script build
          echo Finished running npm commands
      - name: Set env to staging
        if: endsWith(github.ref, '/develop')
        run: |
          echo "AWS_S3_BUCKET=dev.trinitymutualaid.com" >> $GITHUB_ENV
      - name: Set env to production
        if: endsWith(github.ref, '/main')
        run: |
          echo "AWS_S3_BUCKET=trinitymutualaid.com" >> $GITHUB_ENV
      - uses: awact/s3-action@master
        env:
          SOURCE_DIR: './frontend/build'
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
