name: S3-Update-Static

on:
  push:
    branches: 
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Create .env file and build
        env:
          REACT_APP_AWS_REGION: ${{  secrets.REACT_APP_AWS_REGION  }}
          REACT_APP_IDENTITY_POOL_ID: ${{  secrets.REACT_APP_IDENTITY_POOL_ID  }}
          REACT_APP_USER_POOL_ID: ${{  secrets.REACT_APP_USER_POOL_ID  }}
          REACT_APP_USER_POOL_WEB_CLIENT_ID: ${{  secrets.REACT_APP_USER_POOL_WEB_CLIENT_ID  }}
          REACT_APP_REST_API: ${{  secrets.REACT_APP_REST_API  }}
          REACT_APP_S3_BUCKET: ${{  secrets.REACT_APP_S3_BUCKET  }}
          REACT_APP_S3_BUCKET_URL: ${{  secrets.REACT_APP_S3_BUCKET_URL  }}
        run: |
          cd ./frontend
          npm install
          cat << EOF > .env
          REACT_APP_AWS_REGION=${{ secrets.REACT_APP_AWS_REGION }}
          REACT_APP_IDENTITY_POOL_ID=${{ secrets.REACT_APP_IDENTITY_POOL_ID }}
          REACT_APP_USER_POOL_ID=${{ secrets.REACT_APP_USER_POOL_ID }}
          REACT_APP_USER_POOL_WEB_CLIENT_ID=${{ secrets.REACT_APP_USER_POOL_WEB_CLIENT_ID }}
          REACT_APP_REST_API=${{ secrets.REACT_APP_REST_API }}
          REACT_APP_S3_BUCKET=${{ secrets.REACT_APP_S3_BUCKET }}
          REACT_APP_S3_BUCKET_URL=https://${{ secrets.REACT_APP_S3_BUCKET }}.s3.amazonaws.com
          EOF
          cat .env
          npm run-script build
      - name: Set env to staging
        if: endsWith(github.ref, '/develop')
        run: |
          echo "AWS_S3_BUCKET=dev.trinitymutualaid.com" >> $GITHUB_ENV
      - name: Set env to production
        if: endsWith(github.ref, '/main')
        run: |
          echo "AWS_S3_BUCKET=trinitymutualaid.com" >> $GITHUB_ENV
      - uses: awact/s3-action@master
        env:
          SOURCE_DIR: './frontend/build'
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
