# This is a basic workflow to help you get started with Actions

name: Production CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - main
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      name: Checkout Project
    # Set up all my various tools (node, aws cli/aws sam)
    - name: Get Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Get Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Get Sam
      uses: aws-actions/setup-sam@v1
    - name: Sign in to AWS-CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    # Activate the appropriate build environment
    - name: Activate Staging Build
      if: endsWith(github.ref, '/develop')
      run: |
        echo "DEPLOY_ENV=staging" >> $GITHUB_ENV
    - name: Activate Production Build
      if: endsWith(github.ref, '/main')
      run: |
        echo "DEPLOY_ENV=production" >> $GITHUB_ENV
    # Build and deploy
    - name: Build Payload
      run: |
        cd ./lambdas/app
        npm install
        cd ..
        sam build
    - name: Deploy to Cloudformation
      run: |
        cd ./lambdas
        sam deploy --config-env $DEPLOY_ENV --no-confirm-changeset --no-fail-on-empty-changeset
